### ISSUE TITLE
[JOSS review] Conflicting licenses

### ISSUE THREAD

**Issue by pboesu** [UniNE-CHYN/hytool#1]
The repository contains a MIT license at the top level (https://github.com/pboesu/hytool/blob/master/LICENSE), but a GNU GPL v3 in the package documentation (https://github.com/pboesu/hytool/blob/master/html/license.txt) . Please harmonize the license terms.

**Comment by philipperenard** [comment]
Thank you for spoting this issue. I realized that there were also some other inconsistencies in previous pieces of the code which were refering to the GNU license that I initially used (most of the dmo files). I searched systematically and replaced the obsolete references to the GNU license. Now, it should be fine.
