### ISSUE TITLE
[JOSS review] lack of unit tests

### ISSUE THREAD

**Issue by pboesu** [UniNE-CHYN/hytool#3]
There are no automated tests as far as I can see, and as far as I can see no use is made of MATLAB's testing framework.

I am not familiar enough with MATLAB toolboxes or the MATLAB community to know whether or not this is standard practice.

**Comment by philipperenard** [comment]
I was not aware of the existence of the testing framework existing in matlab. As far as I know, it is not yet a standard procedure. But, I believe that it should change. I did a first test and it seems to work very nicely. I will implement it progressively, but it will take me some time. I may not be able to make this change rapidly.
