### ISSUE TITLE
[JOSS review] Lack of community guidelines

### ISSUE THREAD

**Issue by pboesu** [UniNE-CHYN/hytool#4]
JOSS considers it good practice to provide communite guidelines for software users who want to 
1) Contribute to the software 
2) Report issues or problems with the software 
3) Seek support 

Please consider adding such guidelines to the documentation.

**Comment by philipperenard** [comment]
This is a very good suggestion. I have added such guidelines in the Wiki pages. I am not very familiar of this type of information, I tried to provide the main information. Let me know if you have additional suggestions.

**Comment by pboesu** [comment]
That looks great!
